### ISSUE TITLE
Why ParamsValueError code is 500 ? validate params errorCode should be 400 ?

### ISSUE THREAD

**Issue by DanielZhui** [Eastwu5788/pre-request#136]
![image](https://user-images.githubusercontent.com/44571398/147224008-470380c9-d720-4b83-a394-f884274424d7.png)

**Comment by Eastwu5788** [comment]
Thanks for your report, bug i think `500 INTERNAL SERVER ERROR` is response from flask, because you don't catch `ParamsValue Error`. 
You can use the code just like below to catch this error and response anything you want.

```
@app.errorhandler(ParamsValueError)
def params_value_error(e):
    return pre.fmt_resp(e)
```
For more details, You can customize the response format by viewing this documentation here `https://pre-request.readthedocs.io/en/master/customize.html#response`
